version: '3.4'

volumes:
  datafiles:

services:
  db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: Root0++
        MYSQL_USER: newuser
        MYSQL_PASSWORD: pass@word1234
        MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
      - "./sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always

  asp.net_webapi6:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
#      - "7095:443"
      - "5000:80"
    depends_on:
      - db
    environment:
#      - ConnectionStrings__DefaultConnection=server=localhost;port=3306;user=newuser;password=pass@word1234;database=demo
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://+:5000
      - DBHOST=db
    restart: always