# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  asp.net_webapi6:
    build:
      context: "/home/aschapov/RiderProjects/ASP.NET6_WebAPI/ASP.NET_WebAPI6"
      dockerfile: "./Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/ASP.NET_WebAPI6.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "asp.net_webapi6:dev"
    ports: []
    volumes:
    - "/home/aschapov/.nuget/packages:/root/.nuget/packages"
    - "/home/aschapov/RiderProjects/ASP.NET6_WebAPI/ASP.NET_WebAPI6:/app:rw"
    - "/home/aschapov/RiderProjects/ASP.NET6_WebAPI:/src:rw"
    working_dir: "/app"
